### ISSUE TITLE
Cross-server chat is broken since PGM channels refactoring

### ISSUE THREAD

**Issue by calcastor** [PGMDev/Community#79]
Cross-server chat is no longer functional since https://github.com/PGMDev/PGM/pull/1423

This is tested on OCC with both 7b3e9ba1763b2c1008a6b1b5b0b5dc5729599d6b and rebased https://github.com/PGMDev/Community/pull/78

No errors appear to be thrown

**Comment by applenick** [comment]
Hm, very odd. I would have thought #78's changes would resolve the issue. I'll investigate more on this soon.

**Comment by calcastor** [comment]
```
[08:00:59 WARN]: org.apache.commons.lang.UnhandledException: Plugin Community v0.2-SNAPSHOT (git-49515b2) generated an exception while executing task 133
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
        at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: com.google.gson.JsonIOException: Interfaces can't be instantiated! Register an InstanceCreator or a TypeAdapter for this type. Interface name: tc.oc.pgm.api.channels.Channel
        at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:136)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.createAccumulator(ReflectiveTypeAdapterFactory.java:427)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:383)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:433)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:393)
        at com.google.gson.Gson.fromJson(Gson.java:1227)
        at com.google.gson.Gson.fromJson(Gson.java:1137)
        at com.google.gson.Gson.fromJson(Gson.java:1047)
        at com.google.gson.Gson.fromJson(Gson.java:982)
        at dev.pgm.community.network.subs.types.ChatSubscriber.onReceiveUpdate(ChatSubscriber.java:21)
        at dev.pgm.community.network.subs.NetworkSubscriber.onMessage(NetworkSubscriber.java:41)
        at redis.clients.jedis.JedisPubSub.process(JedisPubSub.java:152)
        at redis.clients.jedis.JedisPubSub.proceed(JedisPubSub.java:125)
        at redis.clients.jedis.Jedis.subscribe(Jedis.java:2898)
        at dev.pgm.community.network.types.RedisNetworkFeature.lambda$asyncSubscribe$0(RedisNetworkFeature.java:82)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:64)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 4 more
```
